[build]
  command = """
  curl -fsSL https://fvm.app/install.sh | bash &&
  export PATH="$HOME/.pub-cache/bin:$PATH" &&
  fvm install &&
  fvm flutter config --enable-web &&
  fvm flutter build web --release
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"